db:
   url: jdbc:postgres://hostname:5432/databasename
   username: "secretsmanager://prod-template-rds-username"
   password: "secretsmanager://prod-template-rds-password"
   minimumIdle: 16
   maximumPoolSize: 32
